### ISSUE TITLE
Bug na filtragem por categoria

### ISSUE THREAD

**Issue by GoliasVictor** [lucascesar918/MaisCultura#27]
### **Descrição**
O filtro de categoria na pagina de eventos faz com que eventos que não deveriam desaparecerem, apesar de estarem lá e estar ná categoria filtrada.

### **Como reproduzir**
1. Abra a pagina de eventos
2. Aperte na categoria esporte
3. Veja na parte do desenvolvedor, que mesmo os eventos existindo e estarem marcados como display block, mesmo assim eles não aparecem

### **Screenshots**
![image](https://user-images.githubusercontent.com/61102741/204114643-d17b354d-2dbe-4499-a3b8-0aadcea105ab.png)

**Comment by lucascesar918** [comment]
![Screenshot_20221126-221321.png](https://user-images.githubusercontent.com/52894434/204114872-8cf52f7d-8249-4c7f-bcba-3d88d963f13f.png)

**Comment by GoliasVictor** [comment]
A tua mente colapsando kkkkkkkkkk
